				<footer id="footer" class="container">
					<div class="row 200%">
						<div class="12u">

							<!-- Contact -->
								<section>
									<ul class="contact">
										<li><a class="icon fa-envelope" href="mailto:contato (arroba) mentebinaria (ponto) com.br"><span class="label">Email</span></a></li>
										<li><a class="icon fa-slack" target="_blank" href="http://irc.netsplit.de/channels/details.php?room=%23MenteBinaria&net=freenode"><span class="label">IRC</span></a></li>
										<li><a class="icon fa-facebook" target="_blank" href="https://www.facebook.com/mente.binaria"><span class="label">Facebook</span></a></li>
										<li><a class="icon fa-twitter" target="_blank" href="https://twitter.com/MenteBinaria"><span class="label">Twitter</span></a></li>
										<li><a class="icon fa-github" target="_blank" href="https://github.com/merces"><span class="label">GitHub</span></a></li>
										<li><a class="icon fa-github-alt" target="_blank" href="https://gist.github.com/merces"><span class="label">Gist</span></a></li>
										<li><a class="icon fa-rss" target="_blank" href="rss"><span class="label">RSS</span></a></li>
									</ul>
								</section>

						</div>
					</div>

				</footer>
