					<ul>
						<li><a href=".">Home</a></li>
						<li><a href="textos">Artigos</a></li>
						<li><a href="https://blog.mentebinaria.com.br/" target="_blank">Blog</a></li>
						<li>
							<a>Projetos</a>
							<ul>

								<li>
									<a href="projetos#hardware">Hardware</a>
									<ul>
										<li><a href="#">Portable SNES</a></li>
										<li><a href="#">Z80</a></li>

									</ul>
								</li>
								<li><a href="musica">Música</a></li>
								<li>
									<a href="projetos#software">Software</a>
									<ul>
										<li><a href="#aleph">Aleph</a></li>
										<li><a href="#bashacks">bashacks</a></li>
										<li><a href="#filegrab">FileGrab</a></li>
										<li><a href="#hdump">hdump</a></li>
										<li><a href="#openvaccine">OpenVaccine</a></li>
										<li><a href="#pev">pev</a></li>
										<li><a href="#libpe">libpe</a></li>
										<li><a href="#usbforce">USBForce</a></li>
									</ul>
								</li>
								<li><a href="maicon">Tirinhas do Maicon</a></li>
								
							</ul>
						</li>
						<li><a href="downloads">Downloads</a></li>
						<li>
							<a href="treinamentos">Treinamentos</a>
							<ul>
								<li><a href="treinamentos#le">Linux Extreme</a></li>
								<li><a href="treinamentos#rfs">Reversing from scratch</a></li>
							</ul>
						</li>
						<li><a href="notas">Notas</a></li>
						<li><a href="no-sidebar.html">Palestras</a></li>
						<li><a href="no-sidebar.html">FAQ</a></li>
					</ul>